import {useState, useEffect} from 'react'
import  Main  from '../components/Main';
import Head from 'next/head'
import Header from '../components/Header';
import Nosotros from '../components/sections/Nosotros';
import useMediaQuery from '../hooks/useMediaQuery';
import Servicios from '../components/sections/Servicios';
import Covid from '../components/sections/Covid';
import Flota from '../components/sections/Flota';

const Index = () => {

    // break en width 640px
    const [breakSm, setBreakSm] = useState(null);

    // break en width 768px
    const [breakMd, setBreakMd] = useState(null);

    // break en width 1024px
    const [breakLg, setBreakLg] = useState(null);

    // break en width 1280px
    const [breakXl, setBreakXl] = useState(null);

    // break nosotros section title
    const [nosotrosBreak, setNosotrosBreak] = useState(false);

    return (
        <>
            <Head>
                <title>Taxi Seguro</title>
                <meta name="description" content="Generated by create next app" />
                <meta charset="UTF-8"/>
                <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header 
                setBreakSm= {setBreakSm}
                setBreakMd = {setBreakMd}
                setBreakLg = {setBreakLg}
                setBreakXl = {setBreakXl}
                setNosotrosBreak = {setNosotrosBreak}
            />
            <Main>
                <Nosotros nosotrosBreak = {nosotrosBreak}/>
                <Servicios/>
                <Covid/>
                <Flota/>
            </Main>
        </>
    );
}

export default Index;